apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: node-web-app-tt
  namespace: node-web-project
spec:
  params: 
  - name: git-repo-url
  - name: git-repo-name
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: node-web-app-pipeline-run-
      namespace: node-web-project
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: node-web-app-pipeline
      params:
      - name: deployment-name
        value: $(tt.params.git-repo-name)
      - name: git-url
        value: $(tt.params.git-repo-url)
      - name: git-revision
        value: $(tt.params.git-revision)
      - name: IMAGE
        value: image-registry.openshift-image-registry.svc:5000/node-web-project/web-node-app:latest
      workspaces:
      - name: shared-workspace
        persistentVolumeClaim:
          claimName: my-claim

--- 

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: node-web-app-tb
  namespace: node-web-project
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.url)
  - name: git-revision
    value: $(body.head_commit.id)
  - name: git-repo-name
    value: $(body.repository.name)

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: node-web-app
  namespace: node-web-project
spec:
  serviceAccountName: pipeline
  triggers:
    - name: node-web-app-trigger
      bindings:
        - ref: node-web-app-tb
      template:
        name: node-web-app-tt
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-node-web-app
  namespace: node-web-project
spec:
  to:
    kind: Service
    name: el-node-web-app
    weight: 100